#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


gunicorn server_chat.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers=$(python -c 'import multiprocessing; print(multiprocessing.cpu_count() * 2 + 1)') --threads=3 --timeout 600 --access-logfile - --error-logfile -


